# ML#1 Exercises 

### solutions by Konrad Krawczyk

In [6]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [1]:

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [2]:
print(a*b)

[ 4 10 18]


In [4]:
c = np.array([15,23,57])
cSum = np.sum(c)
cLen = len(c)
cMean = cSum / cLen
print(cMean)

31.6666666667


In [8]:
def std(arr):
    arrMean = np.mean(arr)
    arrSq = np.square(arr-arrMean)
    arrSum = np.sum(arrSq)
    arrNum = arrSum/(len(arr)-1)
    arrStd = np.sqrt(arrNum)
    print(arrStd)
    
std(c)

22.3009715782


In [21]:
d = arange(128) #create an 1-dimensional array of ints from 0 to 127
dOdd = d[0:len(d):2] #get even-indexed elements of the array 
print(np.sum(dOdd)) #sum'em up

4032


In [23]:
e = arange(1024)
e = e[0:512:1]
print(e)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [32]:
#Exercise 6
e = arange(1024)
e = e[21:42:1]
print(e)

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]


In [36]:
#Exercise 7
e = arange(1024)
e = e[::-1] ## Reversed to check if it works for sure
f = np.array([5,8,12,15,18])
g = e[f-1]
print(g)

[1019 1016 1012 1009 1006]


In [37]:
#Exercise 8
def revArr(rng):
    arr = arange(rng)
    arr = arr[::-1]
    print(arr)
    
revArr(128)

[127 126 125 124 123 122 121 120 119 118 117 116 115 114 113 112 111 110
 109 108 107 106 105 104 103 102 101 100  99  98  97  96  95  94  93  92
  91  90  89  88  87  86  85  84  83  82  81  80  79  78  77  76  75  74
  73  72  71  70  69  68  67  66  65  64  63  62  61  60  59  58  57  56
  55  54  53  52  51  50  49  48  47  46  45  44  43  42  41  40  39  38
  37  36  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21  20
  19  18  17  16  15  14  13  12  11  10   9   8   7   6   5   4   3   2
   1   0]


In [41]:
#Exercise 9
a = np.random.rand(128)
aTrim = a[a<=0.5]
print(aTrim)

[ 0.34429349  0.21518682  0.11159926  0.11754131  0.44596642  0.11886396
  0.41910312  0.10455032  0.40630507  0.43617363  0.06212573  0.4287802
  0.49734308  0.17299583  0.21723734  0.2702522   0.48622385  0.22295053
  0.17552216  0.34900414  0.24668098  0.01160922  0.24154446  0.24363007
  0.47046103  0.43172323  0.43915356  0.27559822  0.23257951  0.34699106
  0.37608225  0.49844026  0.3654065   0.11217764  0.19844399  0.16921384
  0.04738094  0.21757168  0.25200135  0.29515153  0.49564617  0.06776771
  0.28155415  0.06093503  0.14464778  0.080772    0.1592508   0.1433811
  0.29949373  0.05037588  0.01055938  0.09373932  0.09960988  0.03292911
  0.13807824  0.48835606  0.36152656  0.34129996  0.09365663  0.43309358
  0.26368802  0.4191634   0.02680676]


In [47]:
#Exercise 2.1
def getRow(num):
    x = np.random.rand(24,24)
    print(x[num,:])
getRow(10)

[ 0.81226345  0.44281766  0.84395594  0.64736744  0.78582928  0.89623514
  0.70207123  0.50143181  0.66102323  0.05796448  0.67900605  0.22363962
  0.78149596  0.92136129  0.0151691   0.55091538  0.94509649  0.5511257
  0.09072216  0.73359539  0.15456547  0.73255665  0.62052918  0.82826667]


In [73]:
#Exercise 2.2
def getColumn(col):
    a = np.arange(24).reshape((3, 8))
    print(a[:,col])
getColumn(7)

[ 7 15 23]


In [151]:
#Exercise 2.3
a = np.arange(24).reshape((3, 8))
a = a.astype(np.float)
aMeans = np.mean(a, axis=0).reshape((1,8))
print(a)
print(aMeans)

[[  0.   1.   2.   3.   4.   5.   6.   7.]
 [  8.   9.  10.  11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.  21.  22.  23.]]
[[  8.   9.  10.  11.  12.  13.  14.  15.]]


In [152]:
#Exercise 2.4 -- I can't seem to find a solution to this one unfortunately :/
#aSbt = a-aMeans
#print(aSbt)
aSbt = np.subtract(a,aMeans)
print(aSbt)

[[-8. -8. -8. -8. -8. -8. -8. -8.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.]]


In [157]:
#Exercise 3.1
a = np.arange(24).reshape(1,24)
print(a)
#Exercise 3.2
a = np.arange(24).reshape(24,1)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [161]:
#Exerise 3.3
a = np.arange(24).reshape(3,8) #Generate a matrix 3x8
print(a[2])
#value a[i] returns the i-th feature vector in a matrix. Values from 0 up to number of features -1 (zero-based indexing)

[16 17 18 19 20 21 22 23]


In [165]:
#Exercise 3.4
a = np.arange(15).reshape(3,5)
v = np.array([10,20,10,20,10])
print(a-v)

[[-10 -19  -8 -17  -6]
 [ -5 -14  -3 -12  -1]
 [  0  -9   2  -7   4]]


In [169]:
#Exercise 3.5
v = np.array([10,20,10]).reshape(3,1)
print(a-v)

[[-10  -9  -8  -7  -6]
 [-15 -14 -13 -12 -11]
 [  0   1   2   3   4]]


In [171]:
#Exercise 4.1
f = np.array([4,5,4,5,4])
g = np.array([5,6,5,6,5])
h = np.inner(f,g)
print(h)

120


In [173]:
#Exercise 4.2
print(a*g)

[[ 0  6 10 18 20]
 [25 36 35 48 45]
 [50 66 60 78 70]]


In [179]:
#Exercise 4.3
k = np.transpose(g)
print(k)
#The shape is exactly the same. Am I making a mistake?

[5 6 5 6 5]


In [188]:
A = arange(15).reshape(3,5)
v3 = np.array([3,5,3])
print(v3@A) #result of v3 @ A
v31 = v3.reshape(3,1)
#print(v31@A) --- v31 @ A returns an ERROR
print(v31.T@A) # therefore, they have to be transpose before operations like this

[55 66 77 88 99]
[[55 66 77 88 99]]
